package com.netralabs.quality.rules;

import com.itextpdf.kernel.pdf.PdfDictionary;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfName;
import com.itextpdf.kernel.pdf.PdfString;
import com.itextpdf.kernel.xmp.XMPMeta;
import com.netralabs.Rule;
import com.netralabs.basic.content.Context;
import com.netralabs.domain.PDFUACheckpoint;
import com.netralabs.domain.Severity;
import com.netralabs.metadata.XMPMetaHelper;
import com.netralabs.report.FindingDTO;

import java.util.ArrayList;
import java.util.List;

/**
 * PAC "Validity of document title" — evaluates the document title in three
 * severities:
 * <ul>
 *   <li>PASSED when a title is present, non-blank, and does not look
 *       auto-generated.</li>
 *   <li>WARNING (matching PAC "Document metadata title may have been auto-generated")
 *       when a title is present but its shape suggests it was produced by the
 *       authoring tool: a raw filename (.pdf/.docx/.doc suffix), a
 *       "Microsoft Word - ..." prefix, an all-digit stem, or a generic
 *       "Untitled"/"Document".</li>
 *   <li>ERROR when no title is present in XMP or /Info.</li>
 * </ul>
 */
public class ValidateDocumentTitle implements Rule {

  private static final String PAC_AUTO_MSG =
      "Document metadata title may have been auto-generated";

  @Override
  public List<FindingDTO> run(Context ctx) {
    List<FindingDTO> out = new ArrayList<>();
    PdfDocument pdf = ctx.pdf();

    String title = extractXmpTitle(pdf);
    if (title == null || title.trim().isEmpty()) title = extractInfoTitle(pdf);

    if (title == null || title.trim().isEmpty()) {
      out.add(new FindingDTO(Severity.ERROR, PDFUACheckpoint.Q_DOC_TITLE_VALIDITY, 0, null,
          "Document title is missing or blank"));
      return out;
    }
    if (looksAutoGenerated(title)) {
      out.add(new FindingDTO(Severity.WARNING, PDFUACheckpoint.Q_DOC_TITLE_VALIDITY, 0, null, PAC_AUTO_MSG));
      return out;
    }
    out.add(new FindingDTO(Severity.PASSED, PDFUACheckpoint.Q_DOC_TITLE_VALIDITY, 0, null));
    return out;
  }

  static boolean looksAutoGenerated(String title) {
    String t = title.trim();
    if (t.isEmpty()) return true;
    String lower = t.toLowerCase();

    if (lower.startsWith("microsoft word - ")) return true;
    if (lower.equals("untitled") || lower.equals("untitled document") || lower.equals("document")) return true;
    if (lower.endsWith(".pdf") || lower.endsWith(".docx") || lower.endsWith(".doc")
        || lower.endsWith(".pptx") || lower.endsWith(".ppt")
        || lower.endsWith(".xlsx") || lower.endsWith(".xls")) return true;

    // Stem-only numeric: e.g. "419663" — clearly a file identifier, not a title
    int dot = lower.lastIndexOf('.');
    String stem = dot > 0 ? lower.substring(0, dot) : lower;
    return stem.chars().allMatch(Character::isDigit);
  }

  private static String extractXmpTitle(PdfDocument pdf) {
    XMPMeta xmp = XMPMetaHelper.tryGetXmpMeta(pdf);
    if (xmp == null) return null;
    try {
      int n = xmp.countArrayItems("http://purl.org/dc/elements/1.1/", "title");
      for (int i = 1; i <= n; i++) {
        String v = xmp.getArrayItem("http://purl.org/dc/elements/1.1/", "title", i).getValue();
        if (v != null && !v.trim().isEmpty()) return v;
      }
    } catch (Exception ignore) {}
    return null;
  }

  private static String extractInfoTitle(PdfDocument pdf) {
    PdfDictionary info = pdf.getTrailer().getAsDictionary(PdfName.Info);
    if (info == null) return null;
    PdfString t = info.getAsString(PdfName.Title);
    return t == null ? null : t.toUnicodeString();
  }
}